apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
{{-range $k, $v := .Values.mysql.secret }}
  {{ $k | upper }}: {{ $v | quote }}
{{- end }}
