# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Values.mysql.service.ports.name }}
    port: {{ .Values.mysql.service.ports.port }}
  clusterIP: {{ .Values.mysql.service.clusterIP }}

# pod-name.service-name.namespace.svc.cluster.local
# pod-name.service-name
# mysql-0.mysql.mysql.svc.cluster.local