apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.mysql.statefulSet.replicas }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.mysql.statefulSet.name }}
        image: {{ .Values.mysql.statefulSet.repository }}:{{ .Values.mysql.statefulSet.version }}
        env:
        {{- range $k := .Values.mysql.secrets }}
        - name: {{ $k | upper }}
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: {{ $k | upper }}
        {{- end }}
        resources:
          requests:
            {{ .Values.mysql.statefulSet.resources.requests }}
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          {{ .Values.mysql.statefulSet.livenessProbe }}
        readinessProbe:
          {{ .Values.mysql.statefulSet.readinessProbe }}
      volumes:
      - name: config-map
        configMap:
          name: mysql
      tolerations:
      {{- range .Values.mysql.statefulSet.tolerations }}
        - key: "{{ .key }}"
          operator: "{{ .operator }}"
          value: "{{ .value }}"
          effect: "{{ .effect }}"
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.statefulSet.storage }}
