apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.mysql.statefulSet }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.mysql.statefulSet.name }}
        image: {{ .Values.mysql.statefulSet.repository }}:{{ .Values.mysql.statefulSet.version }}
        env:
        {{- range $k := .Values.mysql.secret }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secrets
              key: {{ $k }}
        {{- end }}
          value: app_db
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: {{ .Values.mysql.statefulSet.resources.requests.cpu }}
            memory: {{ .Values.mysql.statefulSet.resources.requests.memory }}
        livenessProbe:
          exec:
            command: {{ .Values.mysql.statefulSet.livenessProbe.exec.command }}
          initialDelaySeconds: {{ .Values.mysql.statefulSet.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.statefulSet.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.statefulSet.livenessProbe.timeoutSeconds }}
        readinessProbe:
          exec:
            command: {{ .Values.mysql.statefulSet.readinessProbe.exec.command }}
          initialDelaySeconds: {{ .Values.mysql.statefulSet.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.statefulSet.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.statefulSet.readinessProbe.timeoutSeconds }}
      volumes:
      - name: config-map
        configMap:
          name: mysql
      tolerations:
      - key: {{ .Values.mysql.statefulSet.tolerations.key }}
        operator: {{ .Values.mysql.statefulSet.tolerations.operator }}
        value: {{ .Values.mysql.statefulSet.tolerations.value }}
        effect: {{ .Values.mysql.statefulSet.tolerations.effect }}
      affinity: {{ .Values.mysql.statefulSet.affinity }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.statefulSet.storage }}
