global:
 namespace: todoapp

todoapp:
  image:
    name: todoapp
    repository: ikulyk404/todoapp
    version: 4.0.1

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

  configs:
    PYTHONUNBUFFERED: "1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kube2py

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  secret:
    SECRET_KEY: "UUdVMkhseDRWWW1kR2RvTTN6U1BMWm5nTkduMTN4S3NmWm5Hc1lUbVozelpvOUUrKEVlMih5eCx5KHZmdGdoM3NfMHW5amEtaiFkcGViKHp0ZGc0N3gpLWsmazN6Zl05ZSopCg=="
    DB_NAME: "YXBwX2Ri"
    DB_USER: "YXBwX3VzZXI="
    DB_PASSWORD: "MTIzNA=="
    DB_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="

  pv:
    storage: 1Gi

  pvc:
    storage: 1Gi
